#!/usr/bin/env bash #wipe

touch /Users/user/folder/random
size=$(df / | tail -1 | tr -d '%' | awk '{print $5}')
random_string=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
while true; do
    while ((size < 95)); do
        echo $random_string >> /Users/user/folder/random
        done
rm -rf /Users/user/folder/random
done
